### ISSUE TITLE
python 3.4 requirement

### ISSUE THREAD

**Issue by netantho** [joelpx/reverse#32]
Running reverse in python < 3.4 results in the following error (tested with python 3.2):

```
$ ./reverse.py tests/nestedloop1.bin
Traceback (most recent call last):
  File "./reverse.py", line 20, in <module>
    from lib import reverse, parse_args
  File "/home/netantho/reverse/lib/__init__.py", line 24, in <module>
    from lib.disassembler import Disassembler
  File "/home/netantho/reverse/lib/disassembler.py", line 25, in <module>
    from lib.output import print_no_end
  File "/home/netantho/reverse/lib/output.py", line 20, in <module>
    from lib.colors import (color_addr, color_comment, color_keyword, color_type,
  File "/home/netantho/reverse/lib/colors.py", line 21, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

``pathlib`` is [available only from python 3.4](https://docs.python.org/3/library/pathlib.html).

Also, the ``python`` command needs to link to python 3.4 to install capstone.

**Comment by joelpx** [comment]
fixed, thanks !
