### ISSUE TITLE
Docker visual mode

### ISSUE THREAD

**Issue by redfast00** [joelpx/reverse#43]
When I use reverse in Docker, everything works, except visual mode. As soon as I use the 'v' command, it crashes. Will add the error later, but it has to do with curses.

**Comment by joelpx** [comment]
@netantho any ideas ?

**Comment by redfast00** [comment]
So: this is the error.

Traceback (most recent call last):
  File "/reverse/reverse.py", line 30, in <module>
    i = Interactive(ctx)
  File "/reverse/lib/interactive.py", line 381, in __init__
    rl.loop()
  File "/reverse/lib/readline.py", line 123, in loop
    self.process_key(ch)
  File "/reverse/lib/readline.py", line 133, in process_key
    self.mapping[ch]()
  File "/reverse/lib/readline.py", line 325, in k_enter
    self.callback_enter(self.line)
  File "/reverse/lib/interactive.py", line 524, in exec_command
    c.callback_exec(args)
  File "/reverse/lib/interactive.py", line 722, in __exec_v
    Visual(self, self.ctx.dis, o)
  File "/reverse/lib/visual.py", line 103, in __init__
    curses.init_pair(1, 253, 66) # for the highlight search
_curses.error: init_pair() returned ERR

**Comment by BestPig** [comment]
Setting the environment variable `TERM` to `xterm-256color` fixed the problem, but I don't known if it's the proper way to solve it.

**Comment by redfast00** [comment]
@BestPig: just saw in the code that it indeed has to do with color: in docker curses.COLORS is 8. I think you fix will do. :) Would you mind if I made a pull request?

**Comment by joelpx** [comment]
Thanks for the fix !

**Comment by joelpx** [comment]
I've merged your branch.

**Comment by netantho** [comment]
Sorry for the delay, yes lgtm :-)
