### ISSUE TITLE
ImportError: cannot import name 'lib'

### ISSUE THREAD

**Issue by windybaby** [joelpx/reverse#51]
I just finish the installation.
(./requirements.sh 
python3 setup.py install)
However , there meet difficulty,:(

root@kali:~/reverse# reverse
Traceback (most recent call last):
  File "/usr/local/bin/reverse", line 9, in <module>
    load_entry_point('reverse==1.0', 'console_scripts', 'reverse')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/main.py", line 22, in <module>
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/lib/__init__.py", line 25, in <module>
ImportError: cannot import name 'lib'

**Comment by bogdanm** [comment]
Same thing happening here (python 3.4.3, Linux Mint 17)

Traceback:

```
$ reverse exe
Traceback (most recent call last):
  File "/usr/local/bin/reverse", line 9, in <module>
    load_entry_point('reverse==1.0', 'console_scripts', 'reverse')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/main.py", line 22, in <module>
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/lib/__init__.py", line 25, in <module>
ImportError: cannot import name 'lib'
```

**Comment by joelpx** [comment]
Thank you.
I've just succeeded to reproduce the bug, after deleting all my *.pyc files. I don't know where it comes from, but I have indeed push a commit which solves the problem for me.
Can you confirm it's ok for you ?

**Comment by bogdanm** [comment]
No, still no dice. I tried to start from a clean state:

- `git pull origin master`
- `rm -rf build` in the `reverse`/ directory
- `rm -rf /usr/local/lib/python3.4/dist-packages` (well, I actually renamed it, not deleted it :) )
- `./requirements.sh`
- `sudo python3 setup.py install`

The error I get now is a bit different, but still related most likely:

```
$ reverse exe
Traceback (most recent call last):
  File "/usr/local/bin/reverse", line 9, in <module>
    load_entry_point('reverse==1.0', 'console_scripts', 'reverse')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/main.py", line 22, in <module>
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/lib/__init__.py", line 25, in <module>
  File "/usr/local/lib/python3.4/dist-packages/reverse-1.0-py3.4.egg/reverse/lib/database.py", line 34, in <module>
ImportError: cannot import name 'lib'
```

**Comment by joelpx** [comment]
Hum ok, I've pushed  new commit where I removed all these imports.

**Comment by joelpx** [comment]
e92821c85c1a56d5257c515b80344060263c929f

**Comment by bogdanm** [comment]
That seems to have done the trick, thanks! Although I'm on a different machine now. I'll try to install in again on the initial machine tomorrow.
